//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealServer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MealOrderEntities : DbContext
    {
        public MealOrderEntities()
            : base("name=MealOrderEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<bloc> bloc { get; set; }
        public DbSet<customer> customer { get; set; }
        public DbSet<extrameal> extrameal { get; set; }
        public DbSet<meal> meal { get; set; }
        public DbSet<mealkind> mealkind { get; set; }
        public DbSet<mealstate> mealstate { get; set; }
        public DbSet<ordermeal> ordermeal { get; set; }
        public DbSet<ordermealdetail> ordermealdetail { get; set; }
        public DbSet<restaurant> restaurant { get; set; }
    }
}
