//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordermeal
    {
        public int ID { get; set; }
        public int RestaurantID { get; set; }
        public string Kind { get; set; }
        public int TableNum { get; set; }
        public Nullable<int> CustomID { get; set; }
        public int PeopleNum { get; set; }
        public Nullable<System.DateTime> OrderTime { get; set; }
        public Nullable<System.DateTime> PayTime { get; set; }
        public string Comment { get; set; }
    }
}
